# Generated by Django 4.2.4 on 2023-09-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comments_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='text',
        ),
    ]
