# Generated by Django 4.2.4 on 2023-09-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
